import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Footer from "@/components/footer";
import ThemeSwitch from "@/components/theme-switch";
import ThemeContextProvider from "@/context/theme-context";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Oğuzhan Bülbül | Portfolio',
  description: 'Generated by Oğuzhan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}
      >
        <div className="bg-green-100 absolute top-[-6rem] right-[11rem] h-[45rem] w-[55rem] rounded-full blur-[25em] 
        sm:w-[68.75rem] md:right-[-13rem] lg:right-[18rem] xl:right-[23rem] 2xl:right-[30rem] -z-10  dark:bg-[#3f1f1f]"></div>
        <div className="bg-purple-100 absolute top-[-1rem] left-[-35rem] h-[45rem] w-[55rem] rounded-full blur-[25rem] 
        sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] -z-10 dark:bg-[#27244b]"></div>
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <Header />
            {children}
            <Footer />

            <Toaster position="top-right" />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}